### ISSUE TITLE
tendras algun video de como implementar el bot de telegram me serviria de mucha ayuda 

### ISSUE THREAD

**Issue by JJonathanAsgard** [jorg-gr/telegrambot-cacti#1]

**Comment by jorggr** [comment]
Te ofrezco una disculpa, no me da tiempo de realizar un video, posiblemente en un futuro, acabo de actualizarlas las instrucciones del repo, contempla los siguientes pasos:

1.- Generas un backup de la base de datos del cacti
2.- Creas un usuario nuevo y le das permisos para tener acceso a la base de datos de cacti
4.- Creas un virtualenv, lo activas e instalas las librerías como se indica en las instrucciones
5.- Clonas el proyecto dentro de la carpeta de virtualenv
6.- Te posicionas dentro de la carpeta del repo clonado
7.- Remplazas los datos en el .env que generes
8.- Ejecutas el script run_once.py que genera la tabla y toma los datos del .env (Accesos de BD)
9.- Revisas si fue creada la tabla plugin_telegram_bot
10.- Integras al crontab la tarea y le indicas que debe de ejecutar un script execute.sh cada 5 minutos el cual manda a llamar a telegram_bot.py, guardas
11.- Revisas que se este ejecutando o que errores te genera esto lo puedes visualizar en los logs
12.- Revisa que las rutas o paths que agregues correspondan a las ubicaciones en donde clonaste el repo o creaste el virtualenv.

Intentalo, no te rindas.
